apiVersion: v1
kind: Secret
metadata:
  name: docker-creds
  namespace: dev
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImMyVnlaVzQyTVRjNlRHNXRRQ01rTVRZME9UUXdOQT09IgoJCX0KCX0KfQ==
